version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - socket

  socket:
    build: ./socket
    container_name: socket_container
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./socket/.env

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
      - socket
